server.port=8080
server.servlet.context-path=/api

spring.application.name=number-guess

spring.datasource.url=jdbc:mysql://localhost:3306/number_guess
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.signerKey=8fIOaYwLdFXKXngvDoOUViQeV4yINCtY1IPJAt73lYLdbC74BwlrrWVo9POKmBV7