server.port=8080
server.servlet.context-path=/api
spring.application.name=number-guess
spring.datasource.url=jdbc:mysql://localhost:3306/number_guess
spring.datasource.username=root
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
jwt.signerKey=8fIOaYwLdFXKXngvDoOUViQeV4yINCtY1IPJAt73lYLdbC74BwlrrWVo9POKmBV7
game.win-rate=0.05
# VNPay Configuration
vnpay.tmn-code=U9EDAY3T
vnpay.hash-secret=7CCIFQY9GTNNZR72HCS5MAZXWWI5L5H8
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment-result
vnpay.order-type=billpayment
vnpay.locale=vn
vnpay.currency-code=VND